version: '3.1'

services:
  coder_db:
    image: mysql:5.7
    ports:
      - "3312:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: coder_db
      MYSQL_ROOT_USER: ucoder
      MYSQL_USER: ucoder
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret